spring:
  datasource:
    driver-class-name: org.postgresql.Driver

flyway:
  locations: classpath:db/migration,classpath:db/fixtures

stubhub:
  url: https://api.stubhub.com
  listing:
    path: /search/inventory/v2
    page-size: 200
  api:
    token: 6f8f4c0a-090c-32dc-a74b-3fad7b41692a
