server:
  port: 9000

djdapz:
  stubhub:
    schema: local

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stubhub
    password:
    username: devondapuzzo

flyway:
  schemas: ${djdapz.stubhub.schema}
  clean-on-validation-error: true