spring:
  datasource:
    url: jdbc:postgresql://baasu.db.elephantsql.com:5432/pliqbuwe
    password: CjQsgs2hfYuAgRRCmsvfn8a494rWp57G
    username: pliqbuwe
  jpa:
    properties:
      hibernate:
        default_schema: dev

djdapz:
  stubhub:
    schema: dev

flyway:
  schemas: ${djdapz.stubhub.schema}
  clean-on-validation-error: false
  baseline-on-migrate: true