spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stubhub?currentSchema=local
    password:
    username: devondapuzzo
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: local

flyway:
  schemas: local
  locations: classpath:db/migration,classpath:db/fixtures
  clean-on-validation-error: true

stubhub:
  url: https://api.stubhub.com
  path:
    listing: /search/inventory/v2
  api:
    token: 6f8f4c0a-090c-32dc-a74b-3fad7b41692a
